### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Esteban82**
Change the links in Readme.

### CODE REVIEW

**Comment by Esteban82** [comment]
See #6. Ready for review.

**Review by PaulWessel — APPROVED** [review]
This looks good to me - does @meghanrjones  see anything odd? If not then OK to merge.

**Comment by meghanrjones** [comment]
Thanks, @Esteban82. Looks good as long as we're confident the number of sections won't exceed 9 with the added sections for demos and wrappers, otherwise one leading number would make it visually easier to track.

**Comment by Esteban82** [comment]
> "as long as we're confident the number of sections won't exceed 9 with the added sections for demos and wrappers, otherwise one leading number would make it visually easier to track.

Last year we didn't add folders for that. Anycase, we hace two numbers left.

**Pull request merged**
