### PR TITLE
Update links and figures for bash/basics

### PR DESCRIPTION
**Pull request by maxrjones**

### CODE REVIEW

**Comment by Esteban82** [comment]
Max, I just try the script italy.sh on my pc with **gmt-6.4.0-win64.exe** and I got a warning message:

`cosat [WARNING]: No country code matching italy (skipped).  
`

which is related to this command: 
`    gmt coast -R5/20/35/50 -Wthin -Gwheat -Eitaly+gred -Df -Sazure -B -N1/thick,red -JM15c
`
It seems that the dcw-collections are NOT available on Windows.

**Comment by maxrjones** [comment]
oh bummer. thanks for pointing this out. I will revert back to using the ISO codes for tomorrow.

**Comment by Esteban82** [comment]
I am thinking that 'italy" it is not specify in the dcw-collections.txt. Maybe the problems it is not there.

**Comment by maxrjones** [comment]
What do you get from `gmt --show-dcw`?

For me, the code with "italy" works using the following installed via conda.
```
gmt 6.4.0
dcw 2.1.1
gshhg 2.3.7
```

**Comment by Esteban82** [comment]
Yes, the same versions. I asked @joa-quim (about an example with -RScandinavia) and also got the same error.

**Comment by maxrjones** [comment]
I can reproduce the failure using the release testbot - https://github.com/GenericMappingTools/gmt-release-testbot/runs/7189220705?check_suite_focus=true, but cannot tell you the reason it fails on windows. We will need to avoid using dcw-collections for now during the short course.

**Comment by Esteban82** [comment]
I just test that there is a problem when we give the full name. 

If we use the codes of the dcw-collections (like `SCND` or `IHO28`) ot countries (`IT`) instead of the full name (`Scandinavia` or `"Mediterranean Sea"`, or `italy`) it works. 

```
gmt coast -RScandinavia -Glightgray -B -pdf Scandinavia    # Do NOT work
gmt coast -RSCND -Glightgray -B -pdf Scandinavia    # Works
```

**Comment by PaulWessel** [comment]
Unclear why it does not work for you.  With -Vd I see this:

```
coast [DEBUG]: 1. DCW: Read the Digital Chart of the World from /Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/dcw-gmt-2.1.1/dcw-collections.txt
coast [DEBUG]: DCW: Found 248 countries, 8 countries with states, 275 states, 0 DCW collections and 248 user groups
coast [INFORMATION]: Collection code expanded from Scandinavia to DK,NO,SE [3 countries]
coast [DEBUG]: Requested 3 DCW items: DK,NO,SE
```

So Scandinavia is in the 2.1.1 collections file, no?

**Comment by joa-quim** [comment]
Could it be that dcw.conf that it says it doesn’t found?

This is with -RSCND

coast [DEBUG]: 1. DCW: Read the Digital Chart of the World from C:/progs_cygw/GMTdev/gmt5/master/share/dcw/dcw-countries.txt
coast [DEBUG]: 1. DCW: Read the Digital Chart of the World from C:/progs_cygw/GMTdev/gmt5/master/share/dcw/dcw-states.txt
coast [DEBUG]: Look for file c:/j/dcw.conf
coast [DEBUG]: Look for file c:/j/.gmt/dcw.conf
coast [DEBUG]: Look for file c:/j/.gmt/server/dcw.conf
coast [DEBUG]: Look for file c:/j/.gmt/cache/dcw.conf
coast [DEBUG]: Could not find file dcw.conf
coast [DEBUG]: 1. DCW: Read the Digital Chart of the World from C:/progs_cygw/GMTdev/gmt5/master/share/dcw/dcw-collections.txt
coast [DEBUG]: DCW: Found 248 countries, 8 countries with states, 275 states, 0 DCW collections and 248 user groups
coast [INFORMATION]: Collection code expanded from SCND to DK,NO,SE [3 countries]
coast [DEBUG]: Requested 3 DCW items: DK,NO,SE

**Comment by Esteban82** [comment]
> So Scandinavia is in the 2.1.1 collections file, no?

Yes, it is. I even could make a map of Continetal Portugal (-RPTC). 

So, the DCW-Collections can be used only if we use the Codes (not the full name). 
The same with the countries and states. `-RIT` works, `-Ritaly` don't.

**Pull request merged**
